### ISSUE TITLE
Hi! I like this competent, but i see error : Warning: Unknown props

### ISSUE THREAD

**Issue by Philin-Anton** [moarwick/redux-easy-forms#7]
Warning: Unknown props `errors`, `serverErrors`, `focused`, `touched`, `dirty`, `valuePristine`, `onCheck`, `formKey`, `valueIn`, `valueOut` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

**Comment by Philin-Anton** [comment]
By rules itself.
You need to remove the extra properties before inserting them into the INPUT

export const textField =function (fun, name){
  const textField = Object.assign({}, fun.props( name));
  delete textField.errors;
  delete textField.serverErrors;
  delete textField.focused;
  delete textField.touched;
  delete textField.dirty;
  delete textField.validators;
  delete textField.valuePristine;
  delete textField.onCheck;
  delete textField.formKey;
  delete textField.valueOut;
  delete textField.valueIn;
  return textField
};

example:
const f = this.props.REForms; 
textField (f, 'email');

**Comment by moarwick** [comment]
Unfortunately, React introduced these warnings only recently. Prior to React `15.2`, it simply ignored unsupported props, which allowed for more flexibility, imo. I'll look into updating the package soon, but now it may need custom prop sets per input type and/or component. These obviously vary, so I'm not sure how to solve it cleanly yet, maybe through whitelists.. In the meantime, you can downgrade to `15.1`..
